[package]
name = "chapter8-2"
version = "0.1.0"
authors = ["rimanov2000 <rimanov2000@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
